platform:
  host-url:

  fetching-delay: 10s

  auth:
    # DISABLED, LOGIN_FORM, OAUTH2
    type: DISABLED

    # Must be specified if auth.type is LOGIN_FORM
    login-form-credentials: admin:admin

    # All entries must be specified if auth.type is OAUTH2
    oauth:
      auth-domain:
      client-id:
      client-secret:

puller:
  client:
    max-in-memory-size: 67_108_864
  worker-thread-pool-size: 5

management:
  endpoints:
    enabled: false
  info:
    enabled: true
  health:
    enabled: true